# Generated by Django 5.0.6 on 2024-05-29 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0002_alter_build_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='title',
            field=models.CharField(max_length=400),
        ),
    ]
