# Generated by Django 5.0.6 on 2024-05-25 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='images/%Y/%m/')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=40, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('rarity_level', models.PositiveSmallIntegerField(choices=[(0, 'Common'), (1, 'Rare'), (2, 'Epic'), (3, 'Legendary')], default=0)),
                ('image', models.ImageField(blank=True, upload_to='images/%Y/%m/')),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='items.addon')),
            ],
        ),
    ]
