# Generated by Django 5.0.6 on 2024-05-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
